plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
}

bootJar {
    archiveFileName = 'gateway.jar'
}

dependencies {
    implementation libs.spring.cloud.gateway.webmvc
    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.security
    implementation libs.spring.boot.starter.oauth2.resource.server
    implementation libs.spring.boot.starter.actuator
    implementation libs.spring.boot.starter.validation
    implementation libs.springdoc.openapi
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testImplementation libs.spring.boot.starter.test
    testImplementation libs.spring.security.test
}
